### ISSUE TITLE
#10 Changer le courriel de provenance de jobs au lieu de celui de Julie

### ISSUE THREAD

**Issue by marievecqsb** [mickaelduboisnextal/cqsb#11]
Quand on envoie un courriel Nextal, on voudrait que ça provienne du courriel jobs@cqsb.qc.ca et non de Julie.

**Comment by mickaelduboisnextal** [comment]
Ceci est une demande  de modification est non pas  un bug. Nous ne supportons pas cette fonctionnalité  actuellement pour des raisons de  tracabilité. 

Modifier le comportement actuelle demanderais un  modification importante de notre système.

**Comment by mickaelduboisnextal** [comment]
A discuter plus en détail
