### ISSUE TITLE
Pas de bouton Télécharger quand on envoie un CV aux directions

### ISSUE THREAD

**Issue by marievecqsb** [mickaelduboisnextal/cqsb#13]
SVP ajouter un bouteau DOWNLOAD sur la page quand on transfère un CV aux directions pour pouvoir le télécharger rapidement.
Maintenant, il faut besoin sur la petite flèche, qui ouvre le CV sur une autre page, ensuite cliquer encore et ensuite on peut télécharger. 
Pouvez-vous mettre le bouton télécharger directement sur la page de Nextal après avoir cliqué sur le lien.

**Comment by mickaelduboisnextal** [comment]
Ceci est de  demande de modification du système actuelle. Par  preuve de bonne volonté nous avons décider d'ajouter cette fonction gratuitement.

**Comment by marievecqsb** [comment]
D'accord, merci. Ça marche.
