### ISSUE TITLE
SVP changer l'orthographe d'une raison de refus du candidat

### ISSUE THREAD

**Issue by marievecqsb** [mickaelduboisnextal/cqsb#15]
Il manque un i dans non-qualifié
Je ne trouve pas comment le modifier, est-ce qu'on a les droits pour le faire?

**Comment by mickaelduboisnextal** [comment]
Vouvs devriez etre capable de modifier par vous meme. je viens de le faire pour vous

**Comment by marievecqsb** [comment]
Merci.
Pourrais-tu me dire comment faire? Je ne trouvais pas comment.
