### ISSUE TITLE
Texte de bas de page

### ISSUE THREAD

**Issue by marievecqsb** [mickaelduboisnextal/cqsb#18]
Alerte emploi
L'alerte emploi est un service qui vous permet de vous abonner à des alertes pour un role et une ville.

Changer pour:
L'alerte emploi est un service qui vous permet de vous abonner à des alertes pour être informé.e des postes disponibles dans les régions choisies.

**Comment by mickaelduboisnextal** [comment]
Ceci est une demande de modification et non un bug il sera fera sujet d'une facturation. Souhaitez vous véritable cette modification. 

Cordialement

**Comment by marievecqsb** [comment]
Je ne comprend pas, la phrase ne se dit pas, je propose une nouvelle façon d'écrire une phrase qui est déjà là?

**Comment by mickaelduboisnextal** [comment]
Le site complet à été validé par vos prédécesseurs. Malheureusement chaque personne ne peux pas faire une demande de modification de son contenu.

**Comment by marievecqsb** [comment]
ok alors corriger le mot rôle, il manque un accent.
Avec le nombre d'erreurs d'orthographe qu'on trouve dans les sections de la plateforme encore aujourd'hui, je me dis que vous pourriez faire les corrections qu'on demande.

Nous demandons et redemandons des choses qui n'ont pas été faites, ou que vous dites qui sont corrigées, mais ne le sont pas. Ça devient très mêlant de se rappeler ce qui est supposé fonctionner.

**Comment by mickaelduboisnextal** [comment]
Je comprend et je vous assure que nous faisons de notre mieux pour vous satisfaire au plus vite. Nous sommes une petite structure et espérerons arriver à une situation ou tout vous conviens.

je vais m'arranger pour faire cette modication gratuite

**Comment by mickaelduboisnextal** [comment]
Pouvez vous me dire quelle phrase vous conviendrais en anglais ?

**Comment by mickaelduboisnextal** [comment]
Jattend votre phrase en anglais pour faire la modification

**Comment by marievecqsb** [comment]
J'ai pris le texte qui est en haut de la page finalement. 

français: L'alerte emploi est un service qui vous permet d’être avisé(e) par courriel lorsqu’un type d’emploi dans une région précise devient disponible.

anglais: The job alert is a service that allows you to subscribe to alerts for a particular role and region.

Merci.

**Comment by mickaelduboisnextal** [comment]
Bonjour,

Nous avons mis le texte souhaité par défaut mais nous avons aussi ajouter la possibilité de modifier le text à votre guise. C'est le texte qui se trouve dans le haut de la page de l'alerte emploie qui s'affichera dans le bas de la page aussi. 

Cordialement
