### ISSUE TITLE
Ajouter un note dans le courriel des directeurs

### ISSUE THREAD

**Issue by mickaelduboisnextal** [mickaelduboisnextal/cqsb#2]

**Comment by marievecqsb** [comment]
Quand est-ce que ce sera fait?

**Comment by mickaelduboisnextal** [comment]
Cette fonction viens d'être livré ce matin. 

Nous avons aussi ajouter la possibilité de voir les courriels envoyer aux contacts/directeurs. Si vous allez sur le lieu de l'emploie relié au poste vous aller voir qu'il y a maintenant un onglet "Courriel" vous pourrez vois dans ce dernier tous les courriels envoyé aux contacts/directeurs à présent.

La facture de cette fonction devais vous être envoyé prochainement.

Cordialement
