### ISSUE TITLE
Poste 9289 ne sort pas quand on choisit Jonquière dans les choix de ville

### ISSUE THREAD

**Issue by marievecqsb** [mickaelduboisnextal/cqsb#22]
Place of work : Riverside Regional Elementary School
**Location: Saguenay.**

Le poste semble tagger Saguenay - quand dans la liste de choix sur le site, c'est encore Jonquière. Alors quel est le bon?
Day Care Service Educator 9289
Place of work : Riverside Regional Elementary School
 As soon as possible To June 22, 2023
Publication period
Dec 5, 2022 - Jan 8, 2023
Contract type
Temporary
Job Category
Support personnel
Hourly Salary
From $22.54 To $26.00

**Comment by mickaelduboisnextal** [comment]
C'est corrigé
