### ISSUE TITLE
les postes qui ont terminé leur dates d'affichage ne s'enlèvent pas automatiquement du site web

### ISSUE THREAD

**Issue by marievecqsb** [mickaelduboisnextal/cqsb#23]
Les postes qui ont finit leur date d'affichage devraient automatiquement devenir "unpublished" afin qu'on décide si on les re-publie ou non. C'est pourquoi il y a une date d'affichage... sinon quel en est le but?

On voit des postes qui ont été affichés en sept et octobre, novembre en ce moment, comme les postes: 9332, 9324, etc..... il y en a plusieurs.

Special Education Technician 9332
Place of work : Dollard-des-Ormeaux School
 As soon as possible To June 23, 2022
Publication period
Sep 28, 2022 - Oct 4, 2022

**Comment by mickaelduboisnextal** [comment]
Une correction pour cela est prévue pour la semaine prochaine

**Comment by marievecqsb** [comment]
Allo, Je vois encore les postes plus anciens, exemple:

Special Education Technician 9354
Place of work : St. Vincent School
Publication period: Oct 18, 2022 - Oct 25, 2022

**Comment by marievecqsb** [comment]
ceci n'est pas réglé...
