### ISSUE TITLE
Le poste 9169 est encore vide

### ISSUE THREAD

**Issue by marievecqsb** [mickaelduboisnextal/cqsb#24]
C'est la 3e fois que ça arrive... ??

Secrétaire 9169
Place of work : MEES - Mauricie English Elementary School
 As soon as possible To June 30, 2023
Publication period
Sep 28, 2022 - Jan 3, 2023
Contract type
Replacement
SHARE THIS JOB

**Comment by mickaelduboisnextal** [comment]
Bonjour le poste n'est pas à  nouveaux  vide. Vous avex deux poste  avec le même code qui sont tous les deux publiés 
https://ats.nextal.com/protected/v1/pages/user/index.html#/job/edit/632b4ac923a7ce1ce2557675
https://ats.nextal.com/protected/v1/pages/user/index.html#/job/edit/6384d6d043c04e75ebb4af17

Pour évité que celui qui est vide n'apparaisse sur le site  je viens de retirer la publication
