### ISSUE TITLE
On voudrait ajouter une question quand les gens appliquent pour demander s'ils sont autorisé 

### ISSUE THREAD

**Issue by marievecqsb** [mickaelduboisnextal/cqsb#25]
Julie pense qu'on peux le faire nous même, mais on voudrait valider si c'est ici: 
configurations, candidat, propriétés personnalisées et on change propriété 0 par Autorisation à travailler... ??

Merci.

**Comment by mickaelduboisnextal** [comment]
Malheureusement cette fonction n'est actuellement pas disponible actuellement

**Comment by marievecqsb** [comment]
ok je comprend.
Est-ce que ça pourrait l'être si on en fait la demande?
Julie pensait que vous en aviez déjà discuté et qu'on avait l'option de l'ajouter?
