### ISSUE TITLE
Problème ce matin: les villes n'affichent plus quand on fait une recherche

### ISSUE THREAD

**Issue by marievecqsb** [mickaelduboisnextal/cqsb#28]

**Comment by mickaelduboisnextal** [comment]
Je viens de tester sur le  site carriére et la recherche fonctionne correctement, pouvez vous me donner plus de détail ?

**Comment by marievecqsb** [comment]
Ça fonctionne maintenant. C'était peut-être en lien avec le bug quand Julie a créé le nouveau type de contrat.
