### ISSUE TITLE
Alerte emploi ne fonctionne pas

### ISSUE THREAD

**Issue by mickaelduboisnextal** [mickaelduboisnextal/cqsb#3]

**Comment by marievecqsb** [comment]
Quand est-ce que vous allez faire un suivi à ce sujet?

**Comment by marievecqsb** [comment]
Voici toutes les alerte emploi que je suis inscrite et je ne reçois rien:

List of your job alert subscriptions
Day Care Service Educator in Québec×
Special Education Technician in Québec,Shawinigan,Cap-Santé×
Secondary Teacher in Québec,Kawawachikamach,Chibougamau×
Student Supervisor in Québec,La Tuque,Jonquière,Chibougamau,Cap-Santé,Shannon,Saint-Gabriel-de-Valcartier,Shawinigan,Thetford Mines,Kawawachikamach×
Caretaker Evening, class II in Québec×
Secretary in Québec×
Personnel Management Consultant – Payroll and Employee Benefits in Québec×
School or Center Secretary in Québec×
Elementary Teacher in La Tuque,Québec,Saint-Gabriel-de-Valcartier,Shannon

**Comment by mickaelduboisnextal** [comment]
Je vais regarder une nouvelle fois mais tout à été corriger au dernière nouvelle

**Comment by mickaelduboisnextal** [comment]
Je reviens de faire des tests tout fonctionne voici une vidéo des mes tests :
https://youtu.be/AZFDO-z58GU

**Comment by marievecqsb** [comment]
Merci pour le vidéo, ça semble marcher de ton côté. 
Pour moi, j'ai reçu deux courriels que le 17 novembre. 
de cette adresse: postmaster@nextal.com <postmaster@nextal.com> et jobs (Je te l'envoie en courriel)
j'ai créé 2 alertes avec gmail et mon adresse de cqsb, il me semble, je n'ai rien recu sur gmail.
