### ISSUE TITLE
On ne reçoit pas les alerte emploi avec les emplois choisis dans alerte emploi

### ISSUE THREAD

**Issue by marievecqsb** [mickaelduboisnextal/cqsb#32]
Encore le même problème
nous ne recevons pas les courriels d'alerte
toute l'équipe s'est inscrit à des alertes

**Comment by mickaelduboisnextal** [comment]
Vue que je recois toutes les alertes auxquelles je suis inscrit, je ne comprend pas pourquoi cela ne fonctionnne pas pour vous.

Afin de pouvoir clarifier la situation nous allons ajouter dans l'application :
- le nombre de candidat qui devrais recevoir l'alert
- la liste des candidates qui devrais recevoir des alert sur les postes créer

Cela devrais être disponibles dans 5 a 7 jours.
