### ISSUE TITLE
Plusieurs problèmes dans les 2 derniers jours

### ISSUE THREAD

**Issue by marievecqsb** [mickaelduboisnextal/cqsb#43]
On se demande si vous faites une mise à jour ou quelque chose?

Julie mentionne plusieurs problèmes: des cv triés hier et qui doivent être reclassés aujourd'hui, hier le filtre des villes ne fonctionnait pas, aujourd'hui c'est revenu.

**Comment by mickaelduboisnextal** [comment]
Bonjour Mariéve,

Nous n'avons apporté aucune modification au cours des deux derniéres semaines  les problémes que vous me remonter me semble trés  étrange. Pouvez vous me donner un cas  en  particulier que je regarde les modifications qui aurais pu causer cette situation.
