### ISSUE TITLE
Certains postes ne s'attachent pas au bon lieu

### ISSUE THREAD

**Issue by marievecqsb** [mickaelduboisnextal/cqsb#44]
9576 c'est JSMS mais affiche QHS

**Comment by mickaelduboisnextal** [comment]
C'est corrigé pour ce  poste.

Nous étudions pourquoi cela ce produit. En attendant la maniére de le corrigé est d'aller sur le poste, de modifier le lieux de poste, de  sauvegarder la modification puis de le  remettre sur le bon lieux et de sauvegarder une derniére fois
