### ISSUE TITLE
Partage de cv à hrhiring@cqsb.qc.ca ou aux directions

### ISSUE THREAD

**Issue by marievecqsb** [mickaelduboisnextal/cqsb#45]
On doit être en mesure de partager des cv à hrhiring@cqsb.qc.ca ou aux directions d'école. On se fait dire qu'ils ne peuvent pas ouvrir les cv, on doit alors manuellement les envoyer aux gens.

Ou des fois il n'y a rien ou pas de lien vers le document ou le document n'ouvre pas.

Pouvez-vous régler ce problème?

**Comment by mickaelduboisnextal** [comment]
Bonjour pouvez vous me confirmé que vous utliser bien le bouton "Transférer" en bas de page des postes pour partager le candidat ?

Cordialement,
Mickael

**Comment by marievecqsb** [comment]
c'est le bouton share qui est utilisé.
Le bouton transfert est seulement pour la direction, seulement 1-2 noms est listé.
Mais moi par exemple, quand j'ai fait transférer aux directions, ça arrive qu'ils ne puissent pas ouvrir

**Comment by mickaelduboisnextal** [comment]
Bonjour, 

Pour les directions il faut absolument utilisé le bouton "Transférer" si le lien qui recoivent ne fonctionne pas merci de leur demandé de me transféré le courriel à mickael@nextal.com

Enfin pour le bouton "Partager/Share" nous allons regarder cela immédiatement. 
Cordialement,
Mickael

**Comment by mickaelduboisnextal** [comment]
Bonjour Mariève,

Nous avons validé de notre coté et lors que vous utiliser le bouton transférer les courriels sont bien envoyé et surtout le lien fonctionne bien. Vous pouvez le voir vous meme sur la page directement du "Lieux de l’emploi/Places of work" dans la section "Couriel/Email" tous les courriels envoyé aux directeurs y sont ressencés. Vous pouvez donc tester le lien vous même.

En "Partagé/Share" notre équipe continu son investigation. Si vous avez des courriels d'exemple qui ne marche pas veuillez me les faire suivre.

Cordialement,
Mickael
