### ISSUE TITLE
Alerte emploi ne fonctionne pas

### ISSUE THREAD

**Issue by marievecqsb** [mickaelduboisnextal/cqsb#46]
Je suspectais que l'alerte emploi ne fonctionnait toujours pas, mais je ne m'en suis pas occupée.
La semaine dernière Sarah Mayrand a créé une autre alerte, pour tech en éduc spécialisée pour Québec car on publiait un poste. 
Elle n'a pas reçu d'alerte.
Ça n'a jamais bien fonctionné depuis le début. Ça avait fonctionné un bout quand vous aviez fait des tests avec mon courriel tour de champagne, mais sinon je n'ai jamais eu d'alerte.

**Comment by mickaelduboisnextal** [comment]
Bonjour Marieve Je vous confirme que l'alerte emploie fonctionne je viens moi même de recevoir un courriel pour le poste que vous venez créer 
Secondary Teacher - FSL 9657
Place of work : Jimmy Sandy Memorial School

Je viens de regarder le compte de Sarah et elle n'a pas activé sont compte donc elle ne recevra  pas de courriel temps que cela ne sera pas fait.

Et je viens de regarder il en est d'ailleur ainsi pour :
sarah.mayrand@cqsb.qc.ca
julie.laflamme@cqsb.qc.ca
jennifer.bignell@cqsb.qc.ca

Cordialement,
Mickael

**Comment by marievecqsb** [comment]
ok j'ai fait le message.
Et pour mon compte? Je crois que je t'avais demandé de m'effacer? Est-ce bien le cas?

**Comment by marievecqsb** [comment]
Je crois bien que Sarah a suivi les étapes pour authentifier son compte, j'étais avec elle. Peut-être que les étapes ne sont pas claires. Elle a bien reçu un courriel et a cliqué sur confirmer mon compte.

**Comment by mickaelduboisnextal** [comment]
Oui en effet tu m'avais demandé de supprimer tous les comptes qui était a
tes adresses

**Comment by marievecqsb** [comment]
ok je viens de le refaire pour moi-même. Je vais voir si je reçois les offres..
