### ISSUE TITLE
Poste 9169 vide

### ISSUE THREAD

**Issue by mickaelduboisnextal** [mickaelduboisnextal/cqsb#7]

**Comment by mickaelduboisnextal** [comment]
Le poste 9169 n'est pas vide :  https://cqsb.nextal.co/fr/job-details/jobTitle/6384d6d043c04e75ebb4af17

**Comment by marievecqsb** [comment]
Julie a effacé l'ancien et l'a republié. Ça fait 2 fois que ça fait ça. Il faudrait voir pourquoi.

**Comment by marievecqsb** [comment]
svp me faire un suivi la dessus !

**Comment by mickaelduboisnextal** [comment]
Malheureusement si vous l'avez effacé je ne peux plus faire de recherche. SI le cas ce reproduisait il faudrais fermer le poste uniquement et m'informé.

Merci

**Comment by marievecqsb** [comment]
Nous avons soulevé le problème il y a plusieurs jours/semaines, avant de l'effacer et recommencer? 
Julie l'a effacé car il fallait que les candidats puissent appliquer sur le poste. 
Le temps d'attente a été trop long.
Si ça se reproduit, j'ouvrirai un billet.
